name: Push new version to dist branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies and Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build:local

      - name: Push new version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Built new version
